### ISSUE TITLE
Georeference   export L8_angles

### ISSUE THREAD

**Issue by jerrychoices** [DHI-GRAS/l8_angles#2]
thank you very much! I would like to ask, how do I export the array calculated by python using L8_ANGLES to an img file and give it georeference and projection?Thank you very much！！！

**Comment by j08lue** [comment]
I am sorry, I actually have no idea. I have not used this package in years and am unable to find any code that references it.

But I suspect that the image transform and shape of the 2D angle fields returned is the same as, or very similar to the transform of the original Landsat-8 scene. Just the resolution might be some fraction of the full band resolution or so.

So you can probably copy the image transform from the Landsat-8 band file and then write the 2D angles data into a new file, using the same data. Something like this:

```python
import rasterio
import l8angles

data = l8angles.calculate_angles(
    "./test_ANG.txt",
    angle_type="SOLAR",
    subsample=2,
    bands=[3, 6, 7]
)

bandfile = "./B03.tif"
with rasterio.open(bandfile) as ds:
    profile = ds.profile.copy()

profile.update(dtype=data.dtype, count=data.shape[0])
with rasterio.open("my-angles.tif", "w", **profile) as ds:
    ds.write(data)
```

You might get errors because the angles `data` has a different size than the band data. Then you need to adjust the `transform`, `height`, and `width` in the `profile` and it should work.

**Comment by jerrychoices** [comment]
Thank you very much. I also wrote the same project as your code logic, and investigated and corrected the errors in it. For example, the output of ``data'' is actually a List, which needs to be converted to an array using numpy to output normally. , My implementation code is attached below, thank you for your selfless help!
code as:
`    
data = l8angles.calculate_angles('F:/6s_test/L8angle/LC81240422014350LGN01/LC08_L1TP_124042_20141216_20170416_01_T1_ANG.txt', angle_type='SOLAR',subsample=1, bands=[3])


    sa=data['sun_az']
    m = np.array(sa)
    a_output_path = "F:/6s_test/output"
    output_a = a_output_path + '/' +  'sun_as.tif'
    outputfile = rasterio.open(output_a,'w',driver='Gtiff',crs = band3.crs,transform=band3.transform,dtype='float64',width=band3.width,height = band3.height,count=1)
    outputfile.write(m)   
    outputfile.close()   `

**Comment by j08lue** [comment]
Glad to hear it worked so smoothly!
